version: '3.8'

services:
  heic-converter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4545:4545"
    volumes:
      - heic_uploads:/app/uploads
      - heic_output:/app/output
    environment:
      - NODE_ENV=production
      - PORT=4545
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4545/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - heic-network

volumes:
  heic_uploads:
    driver: local
  heic_output:
    driver: local

networks:
  heic-network:
    driver: bridge